version: '3.7'
services:
    codeserver:
        image: codercom/code-server
        container_name: code
        volumes:
            - {path/to/your/persistent/projects}:/root/projects
            - {path/to/your/persistent/data}:/data
#        If u use https://github.com/jwilder/nginx-proxy (recommended)
#        environment:
#            VIRTUAL_HOST: your.domain.tld
#            VIRTUAL_PORT: 8443
        ports:
          # With SSL
          - "443:8443"
          # With HTTP
          #- "80:8443"
        command: code-server --allow-http --no-auth
#       Connect via network
#        networks:
#            outpost_network:

#networks:
#    outpost_network:
#        external: true
